### ISSUE TITLE
some data  not provided 

### ISSUE THREAD

**Issue by kjyjxy** [OtavioAugusto/RecSys#1]
some data not provided like /home/piim/Documentos/RecSys2017/Movielens test1/ExpandedData/*.txt,/home/piim/Documentos/RecSys2017/Movielens test1/ExpandedData/log_%s.txt,/home/piim/Documentos/RecSys2017/Movielens test1/log.txt,/home/piim/Documentos/RecSys2016/clusters/%s%s/video_prob_cluster_%s.txt,/home/piim/Documentos/RecSys2017/Movielenstest2/clusters/Arrays/RandomChoice/reward_%s_clusters',/home/piim/Documentos/RecSys2017/Movielens LDA/clusters/Arrays/BayesUCB/reward_%s_clusters_test'/home/piim/Documentos/RecSys2017/Movielens LDA/clusters/%s/movie_cluster_%s.txt',and so on

**Comment by OtavioAugusto** [comment]
> some data not provided like /home/piim/Documentos/RecSys2017/Movielens test1/ExpandedData/*.txt,/home/piim/Documentos/RecSys2017/Movielens test1/ExpandedData/log_%s.txt,/home/piim/Documentos/RecSys2017/Movielens test1/log.txt,/home/piim/Documentos/RecSys2016/clusters/%s%s/video_prob_cluster_%s.txt,/home/piim/Documentos/RecSys2017/Movielenstest2/clusters/Arrays/RandomChoice/reward_%s_clusters',/home/piim/Documentos/RecSys2017/Movielens LDA/clusters/Arrays/BayesUCB/reward_%s_clusters_test'/home/piim/Documentos/RecSys2017/Movielens LDA/clusters/%s/movie_cluster_%s.txt',and so on

Hi @kjyjxy ! Actually to use the files path you need to exclude the substring 'home/piim/Documentos/RecSys2017/Movielens (something)/' because this is the path in my personal PC. I'll make some changes in the code soon to dont cause confusion. Thank you!!

**Comment by kjyjxy** [comment]
Maybe you can send the data to me first, I can also try to solve this problem. my email is  lisa2993197949@gmail.com.Thank you

**Comment by OtavioAugusto** [comment]
> Maybe you can send the data to me first, I can also try to solve this problem. my email is [lisa2993197949@gmail.com.Thank](mailto:lisa2993197949@gmail.com.Thank) you

Sorry about the delay, the last months have been insane for me. At next week i'ill refresh this repository, putting the right files. I'm now downloading the files to send for you and push here. One more time, sorry for delay.

**Comment by kjyjxy** [comment]
It doesn't matter. After all, the work is the most important. No matter what, I am very grateful for your reply.

**Comment by OtavioAugusto** [comment]
Hi! The data have been added! If some thing was forgot, please message me

**Comment by kjyjxy** [comment]
OK,that's fine
